"""Attachment Chamber (MainAI V2): a hostile-file ingress trust boundary.

Standalone, isolated, NOT imported by any production runtime path (no app.main import, no
app.guardian/app.privacy_boundary/app.sentinel/app.sovereign_identity/app.life_recovery/
app.operating_shell import from this package). See docs/mainai_v2/
MAINAI_V2_FILE_INGEST_ATTACHMENT_CHAMBER.md for the design.
"""

from app.attachment_chamber.active_content import scan_active_content
from app.attachment_chamber.archive_safety import (
    MAX_COMPRESSION_RATIO,
    MAX_FILES,
    MAX_NESTING_DEPTH,
    MAX_PROCESSING_SECONDS,
    MAX_SINGLE_FILE_UNCOMPRESSED_BYTES,
    MAX_TOTAL_UNCOMPRESSED_BYTES,
    ArchiveEntryResult,
    ArchiveInspectionResult,
    ArchiveSecurityError,
    inspect_zip_archive,
)
from app.attachment_chamber.mime_detection import ATTACHMENT_MAGIC_BYTES, detect_magic_kind, detect_mime, looks_like_text
from app.attachment_chamber.parser_sandbox import (
    BoundedFileHandle,
    ParserBudget,
    ParserFailureResult,
    ParserOutput,
    ParserSandbox,
    SandboxEnforcementStatus,
    run_parser_safely,
)
from app.attachment_chamber.path_safety import (
    UnsafePathError,
    canonical_case,
    detect_double_extension,
    is_hardlinked_elsewhere,
    is_regular_file_not_symlink,
    is_safe_relative_path,
    normalize_filename,
    quarantine_relative_location,
    resolve_quarantine_path,
)
from app.attachment_chamber.service import (
    AttachmentChamberState,
    events_for_attachment,
    new_chamber_state,
    receive_attachment,
    track_artifact,
    transition_quarantine_state,
    verify_receipt_chain_intact,
)
from app.attachment_chamber.service import from_snapshot as identity_from_snapshot
from app.attachment_chamber.service import to_snapshot as identity_to_snapshot
from app.attachment_chamber.preview import (
    MAX_TEXT_PREVIEW_CHARS,
    PreviewKind,
    PreviewNotImplementedError,
    PreviewNotReadyError,
    PreviewResult,
    preview_document,
    preview_image,
    preview_text,
)
from app.attachment_chamber.sanitize import (
    DerivativeKind,
    SanitizationNotImplementedError,
    SanitizedDerivative,
    sanitize_image_reencode,
    sanitize_metadata_stripped_copy,
    sanitize_pdf_render,
    sanitize_plain_text_extraction,
)
from app.attachment_chamber.types import (
    QUARANTINE_TRANSITIONS,
    TERMINAL_QUARANTINE_STATES,
    ActiveContentRisk,
    ActiveContentSignal,
    AttachmentChamberError,
    AttachmentEvent,
    AttachmentIdentity,
    AttachmentSource,
    DetectedType,
    InvalidQuarantineTransitionError,
    MalformedSnapshotError,
    NotFoundError,
    OwnerMismatchError,
    ParserFailure,
    ParserResult,
    QuarantineState,
    ScanResult,
    TerminalQuarantineStateError,
)

__all__ = [
    "ATTACHMENT_MAGIC_BYTES",
    "MAX_COMPRESSION_RATIO",
    "MAX_FILES",
    "MAX_NESTING_DEPTH",
    "MAX_PROCESSING_SECONDS",
    "MAX_SINGLE_FILE_UNCOMPRESSED_BYTES",
    "MAX_TEXT_PREVIEW_CHARS",
    "MAX_TOTAL_UNCOMPRESSED_BYTES",
    "QUARANTINE_TRANSITIONS",
    "TERMINAL_QUARANTINE_STATES",
    "ActiveContentRisk",
    "ActiveContentSignal",
    "ArchiveEntryResult",
    "ArchiveInspectionResult",
    "ArchiveSecurityError",
    "AttachmentChamberError",
    "AttachmentChamberState",
    "AttachmentEvent",
    "AttachmentIdentity",
    "AttachmentSource",
    "BoundedFileHandle",
    "DerivativeKind",
    "DetectedType",
    "InvalidQuarantineTransitionError",
    "MalformedSnapshotError",
    "NotFoundError",
    "OwnerMismatchError",
    "ParserBudget",
    "ParserFailure",
    "ParserFailureResult",
    "ParserOutput",
    "ParserResult",
    "ParserSandbox",
    "PreviewKind",
    "PreviewNotImplementedError",
    "PreviewNotReadyError",
    "PreviewResult",
    "QuarantineState",
    "SandboxEnforcementStatus",
    "SanitizationNotImplementedError",
    "SanitizedDerivative",
    "ScanResult",
    "TerminalQuarantineStateError",
    "UnsafePathError",
    "canonical_case",
    "detect_double_extension",
    "detect_magic_kind",
    "detect_mime",
    "events_for_attachment",
    "identity_from_snapshot",
    "identity_to_snapshot",
    "inspect_zip_archive",
    "is_hardlinked_elsewhere",
    "is_regular_file_not_symlink",
    "is_safe_relative_path",
    "looks_like_text",
    "new_chamber_state",
    "normalize_filename",
    "preview_document",
    "preview_image",
    "preview_text",
    "quarantine_relative_location",
    "receive_attachment",
    "resolve_quarantine_path",
    "run_parser_safely",
    "sanitize_image_reencode",
    "sanitize_metadata_stripped_copy",
    "sanitize_pdf_render",
    "sanitize_plain_text_extraction",
    "scan_active_content",
    "track_artifact",
    "transition_quarantine_state",
    "verify_receipt_chain_intact",
]
