"""Sentinel (MainAI V2, Stages V2-D1..D4): security event normalization, correlation, and
bounded defensive-action requests.

Standalone, isolated, NOT imported by any production runtime path (no app.main import, no
app.guardian or app.privacy_boundary import from this package). See
docs/mainai_v2/MAINAI_V2_SENTINEL_SECURITY.md for the design.
"""

from app.sentinel.canary import build_canary_touch_event
from app.sentinel.correlation import (
    CREDENTIAL_THEFT_PATTERN,
    DEFAULT_CORRELATION_PATTERNS,
    EXFILTRATION_PATTERN,
    MODEL_TAMPERING_PATTERN,
    RANSOMWARE_PATTERN,
    pattern_full_match,
)
from app.sentinel.defensive_action import (
    build_defensive_action_request,
    preauthorization_covers,
    require_bounded_preauthorization,
)
from app.sentinel.rules import RuleRegistry, evaluate_event_against_registry, new_detection_rule, rule_matches_event
from app.sentinel.service import (
    SentinelState,
    from_snapshot,
    install_threat_pack,
    mark_false_positive,
    new_sentinel_state,
    promote_rule,
    propose_rule,
    publish_new_version,
    record_event,
    register_canary,
    revoke_rule,
    rollback_rule,
    to_snapshot,
    verify_event_chain_intact,
)
from app.sentinel.threat_pack import EXAMPLE_TEST_PACK, load_threat_pack
from app.sentinel.types import (
    TRUSTED_RULE_STATES,
    CanaryResource,
    ContainmentRecommendation,
    CorrelationPattern,
    DefensiveAction,
    DefensiveActionRequest,
    DetectionResult,
    DetectionRule,
    EventReceipt,
    IncidentEvidence,
    IncidentState,
    PreauthorizedDefense,
    RequiredIndicator,
    RetentionPolicy,
    RuleState,
    RuleTuningCandidate,
    SecurityConfidence,
    SecurityEvent,
    SecurityEventType,
    SecurityIncident,
    SecurityKnowledgePack,
    SecuritySeverity,
    SecuritySource,
    SecuritySubject,
    SentinelPrivacyViolation,
    SentinelRuleError,
    ThreatClass,
    ThreatPackTestVector,
)

__all__ = [
    "TRUSTED_RULE_STATES",
    "CREDENTIAL_THEFT_PATTERN",
    "DEFAULT_CORRELATION_PATTERNS",
    "EXAMPLE_TEST_PACK",
    "EXFILTRATION_PATTERN",
    "MODEL_TAMPERING_PATTERN",
    "RANSOMWARE_PATTERN",
    "CanaryResource",
    "ContainmentRecommendation",
    "CorrelationPattern",
    "DefensiveAction",
    "DefensiveActionRequest",
    "DetectionResult",
    "DetectionRule",
    "EventReceipt",
    "IncidentEvidence",
    "IncidentState",
    "PreauthorizedDefense",
    "RequiredIndicator",
    "RetentionPolicy",
    "RuleRegistry",
    "RuleState",
    "RuleTuningCandidate",
    "SecurityConfidence",
    "SecurityEvent",
    "SecurityEventType",
    "SecurityIncident",
    "SecurityKnowledgePack",
    "SecuritySeverity",
    "SecuritySource",
    "SecuritySubject",
    "SentinelPrivacyViolation",
    "SentinelRuleError",
    "SentinelState",
    "ThreatClass",
    "ThreatPackTestVector",
    "build_canary_touch_event",
    "build_defensive_action_request",
    "evaluate_event_against_registry",
    "from_snapshot",
    "install_threat_pack",
    "load_threat_pack",
    "mark_false_positive",
    "new_detection_rule",
    "new_sentinel_state",
    "pattern_full_match",
    "preauthorization_covers",
    "promote_rule",
    "propose_rule",
    "publish_new_version",
    "record_event",
    "register_canary",
    "require_bounded_preauthorization",
    "revoke_rule",
    "rollback_rule",
    "rule_matches_event",
    "to_snapshot",
    "verify_event_chain_intact",
]
