"""Sovereign Identity + Key Hierarchy + Device Trust (MainAI V2, Stages V2-G1, V2-G2,
V2-H3).

Standalone, isolated, NOT imported by any production runtime path (no app.main import, no
app.guardian/app.privacy_boundary/app.sentinel import from this package). See
docs/mainai_v2/MAINAI_V2_SOVEREIGN_IDENTITY.md for the design.

Public API is the `IdentityState`-based `service` functions below (enroll_device,
approve_device, grant_device_key, ...) -- app.sovereign_identity.device_trust's own
dict-based functions are internal plumbing `service` delegates to and are not re-exported
here, to avoid two same-named-but-differently-shaped entry points.
"""

from app.sovereign_identity.hardware import (
    ALL_HARDWARE_PROVIDER_CLASSES,
    HardwareIdentityProvider,
    HardwareSecurityKeyProvider,
    OfflineRecoveryCodeProvider,
    OSKeychainProvider,
    PasskeyProvider,
    SecureEnclaveProvider,
    TPMProvider,
    TrustedDeviceShareProvider,
)
from app.sovereign_identity.keys import (
    decrypt_with_dek,
    encrypt_with_dek,
    generate_key_material,
    unwrap_key,
    wrap_key,
)
from app.sovereign_identity.root_authority import (
    ChallengeRecord,
    RootAuthorityProof,
    RootAuthorityState,
    generate_owner_root_keypair,
    sign_challenge,
    verify_root_authority_proof,
)
from app.sovereign_identity.service import (
    IdentityState,
    approve_device,
    enroll_device,
    evaluate_identity_assertion,
    flag_lost_or_compromised,
    from_snapshot,
    grant_device_key,
    grant_sync_scope,
    issue_root_challenge,
    new_identity_state,
    next_key_version,
    register_owner_root_key,
    reject_stale_enrollment,
    require_proof_level,
    revoke_device,
    to_snapshot,
)
from app.sovereign_identity.types import (
    PROOF_LEVEL_ORDER,
    AgentIdentity,
    DeviceIdentity,
    DeviceKeyGrant,
    DeviceRecord,
    DeviceTrustError,
    DeviceTrustLevel,
    EncryptionEnvelope,
    HardwareCapabilityStatus,
    InsufficientProofLevel,
    KeyEnvelope,
    KeyMaterialError,
    KeyPurpose,
    KeyVersion,
    OwnerIdentity,
    OwnerRootCapability,
    ProofLevel,
    ProviderIdentity,
    RecoveryEnvelope,
    RecoveryIdentity,
    RecoveryMethodKind,
    RootSensitiveAction,
    SessionIdentity,
    WrappedKey,
)

__all__ = [
    "ALL_HARDWARE_PROVIDER_CLASSES",
    "PROOF_LEVEL_ORDER",
    "AgentIdentity",
    "ChallengeRecord",
    "DeviceIdentity",
    "DeviceKeyGrant",
    "DeviceRecord",
    "DeviceTrustError",
    "DeviceTrustLevel",
    "EncryptionEnvelope",
    "HardwareCapabilityStatus",
    "HardwareIdentityProvider",
    "HardwareSecurityKeyProvider",
    "IdentityState",
    "InsufficientProofLevel",
    "KeyEnvelope",
    "KeyMaterialError",
    "KeyPurpose",
    "KeyVersion",
    "OSKeychainProvider",
    "OfflineRecoveryCodeProvider",
    "OwnerIdentity",
    "OwnerRootCapability",
    "PasskeyProvider",
    "ProofLevel",
    "ProviderIdentity",
    "RecoveryEnvelope",
    "RecoveryIdentity",
    "RecoveryMethodKind",
    "RootAuthorityProof",
    "RootAuthorityState",
    "RootSensitiveAction",
    "SecureEnclaveProvider",
    "SessionIdentity",
    "TPMProvider",
    "TrustedDeviceShareProvider",
    "WrappedKey",
    "approve_device",
    "decrypt_with_dek",
    "encrypt_with_dek",
    "enroll_device",
    "evaluate_identity_assertion",
    "flag_lost_or_compromised",
    "from_snapshot",
    "generate_key_material",
    "generate_owner_root_keypair",
    "grant_device_key",
    "grant_sync_scope",
    "issue_root_challenge",
    "new_identity_state",
    "next_key_version",
    "register_owner_root_key",
    "reject_stale_enrollment",
    "require_proof_level",
    "revoke_device",
    "sign_challenge",
    "to_snapshot",
    "unwrap_key",
    "verify_root_authority_proof",
    "wrap_key",
]
