"""MainAI Internal Workforce Foundation — Stage T contracts over existing coordination/security.

Reuse (do not duplicate):
  - app.agent_coordination (reachability registry + repo assignments)
  - app.execution_envelopes / app.provider_spend (real authority + spend)
  - app.egress_policy / provider_disclosure_events (egress ledger)
  - app.intelligence_governance (evidence)
  - app.capability_reality (capability status)

This package owns organizational identity, delegation broker contracts, task-scoped
assignment envelopes, context minimization, performance rollups, selection scoring,
failure/takeover, verification policy, cost budgets, hiring lifecycle, and teams.
"""

from app.workforce.authority import (
    AuthorityEnvelopeError,
    TaskScopedAuthority,
    assignment_authority_is_live,
    path_allowed,
    require_live_assignment_authority,
    revoke_assignment_authority,
    tool_class_allowed,
)
from app.workforce.broker import (
    DelegationBrokerError,
    VerificationError,
    cancel_assignment,
    form_team,
    ingest_untrusted_result,
    mark_verification,
    resolve_delegation,
    submit_delegation_request,
)
from app.workforce.context import (
    ContextPackagingError,
    classify_trust_zone,
    create_context_package,
    minimize_for_trust_zone,
)
from app.workforce.cost import (
    CostGovernanceError,
    assert_scopes_allow_spend,
    budget_is_live,
    budget_remaining,
    release_budget_reservation,
    reserve_against_budget,
    set_cost_budget,
    settle_budget_reservation,
)
from app.workforce.failure import (
    FailureTakeoverError,
    alternate_agent_takeover,
    can_safely_retry,
    latest_checkpoint,
    mark_failure,
    record_checkpoint,
    resume_after_restart,
    safe_retry_same_agent,
)
from app.workforce.injection import (
    fail_closed_on_secret_request,
    looks_like_prompt_injection,
    refuse_role_or_tool_self_upgrade,
    scrub_authority_mutations,
)
from app.workforce.lifecycle import (
    LifecycleError,
    advance_lifecycle,
    detect_need_and_create_candidate,
    record_improvement,
    run_hiring_pipeline,
)
from app.workforce.org_view import organization_snapshot
from app.workforce.performance import (
    PerformanceLedgerError,
    get_or_create_rollup,
    record_job_attempt,
    record_verified_outcome,
    verified_success_rate,
)
from app.workforce.provider_worker import (
    ProviderActivationBlocked,
    WorkerExecutionReceipt,
    WorkerRequestEnvelope,
    activation_allowed,
    activation_gate_status,
    assert_no_credentials_in_context,
    build_worker_request_envelope,
    execute_workforce_assignment,
    handoff_to_verification,
    mark_safety_gate,
    reset_safety_gates_for_tests,
)
from app.workforce.activation_commit import (
    PROVIDER_INVOKE_ENABLED,
    activation_commit_status,
    assert_provider_invoke_disabled,
)
from app.workforce.audit_receipt import DelegationAuditReceipt, build_audit_receipt
from app.workforce.kill_switch import (
    KillSwitchError,
    activate_global_emergency_stop,
    activate_global_kill_switch,
    activate_kill_switch,
    activate_owner_stop,
    assert_authority_grant_allowed,
    assert_grant_allowed,
    assert_not_killed,
    clear_global_emergency_stop,
    clear_kill_switch_for_recovery,
    clear_owner_stop,
    get_global_kill_switch,
    get_kill_switch,
    prove_no_reusable_live_authority,
    query_stop_status,
    record_boot_blocked,
    reset_kill_switch_for_tests,
)
from app.workforce.safe_internal_run import (
    SafeInternalRunError,
    SafeInternalRunReport,
    require_safe_internal_readiness,
    run_first_safe_internal_mainai_run,
)
from app.workforce.activation_gates import (
    REQUIRED_ACTIVATION_GATES,
    ActivationDecision,
    ActivationGateSet,
    GateStatus,
    get_activation_gates,
    record_gate_verification,
    require_activation_allowed,
    reset_activation_gates_for_tests,
)
from app.workforce.department_evidence import department_capability_ledger
from app.workforce.first_delegation_scenario import (
    DelegationRunRecord,
    run_low_risk_public_text_delegation,
    run_systemic_research_learning_loop,
)
from app.workforce.first_team import (
    FIRST_TEAM_SPECS,
    bootstrap_first_team,
    inspect_first_team,
)
from app.workforce.staff_manager import (
    StaffManagerError,
    StaffingDecision,
    apply_staffing_decision,
    decide_staffing,
    maybe_retire_obsolete,
)
from app.workforce.registry import (
    AgentNotSelectableError,
    WorkforceRegistryError,
    assert_agent_selectable,
    disable_workforce_agent,
    get_workforce_agent,
    get_workforce_agent_by_key,
    list_workforce_agents,
    register_workforce_agent,
    retire_workforce_agent,
)
from app.workforce.selector import CandidateScore, SelectorError, score_candidates, select_best_candidate
from app.workforce.teams import (
    KNOWN_TEAM_PATTERNS,
    assert_no_automatic_cross_context,
    form_pattern_team,
    package_context_per_member,
)
from app.workforce.types import (
    AGENT_LIFECYCLE_STATUSES,
    FORBIDDEN_EXTERNAL_DISCLOSURE_KINDS,
    INVARIANTS,
    KNOWN_AGENT_TYPES,
    KNOWN_TRUST_ZONES,
    VERIFICATION_STATUSES,
)
from app.workforce.verification import VerificationPolicy, apply_verification_decision, policy_for_risk
from app.workforce.vertical_slice import LowRiskSliceResult, run_low_risk_classification_slice

__all__ = [
    "AGENT_LIFECYCLE_STATUSES",
    "AgentNotSelectableError",
    "PROVIDER_INVOKE_ENABLED",
    "SafeInternalRunError",
    "SafeInternalRunReport",
    "KillSwitchError",
    "DelegationAuditReceipt",
    "activation_commit_status",
    "assert_provider_invoke_disabled",
    "activate_global_kill_switch",
    "activate_kill_switch",
    "activate_owner_stop",
    "activate_global_emergency_stop",
    "assert_authority_grant_allowed",
    "clear_owner_stop",
    "clear_global_emergency_stop",
    "query_stop_status",
    "record_boot_blocked",
    "assert_grant_allowed",
    "assert_not_killed",
    "build_audit_receipt",
    "clear_kill_switch_for_recovery",
    "get_global_kill_switch",
    "get_kill_switch",
    "prove_no_reusable_live_authority",
    "require_safe_internal_readiness",
    "reset_kill_switch_for_tests",
    "run_first_safe_internal_mainai_run",
    "ProviderActivationBlocked",
    "REQUIRED_ACTIVATION_GATES",
    "ActivationDecision",
    "ActivationGateSet",
    "GateStatus",
    "DelegationRunRecord",
    "department_capability_ledger",
    "get_activation_gates",
    "record_gate_verification",
    "require_activation_allowed",
    "reset_activation_gates_for_tests",
    "run_low_risk_public_text_delegation",
    "run_systemic_research_learning_loop",
    "StaffManagerError",
    "StaffingDecision",
    "FIRST_TEAM_SPECS",
    "WorkerExecutionReceipt",
    "WorkerRequestEnvelope",
    "activation_allowed",
    "activation_gate_status",
    "apply_staffing_decision",
    "assert_no_credentials_in_context",
    "bootstrap_first_team",
    "build_worker_request_envelope",
    "decide_staffing",
    "execute_workforce_assignment",
    "handoff_to_verification",
    "inspect_first_team",
    "mark_safety_gate",
    "maybe_retire_obsolete",
    "reset_safety_gates_for_tests",
    "AuthorityEnvelopeError",
    "CandidateScore",
    "ContextPackagingError",
    "CostGovernanceError",
    "DelegationBrokerError",
    "FORBIDDEN_EXTERNAL_DISCLOSURE_KINDS",
    "FailureTakeoverError",
    "INVARIANTS",
    "KNOWN_AGENT_TYPES",
    "KNOWN_TEAM_PATTERNS",
    "KNOWN_TRUST_ZONES",
    "LifecycleError",
    "LowRiskSliceResult",
    "PerformanceLedgerError",
    "SelectorError",
    "TaskScopedAuthority",
    "VERIFICATION_STATUSES",
    "VerificationError",
    "VerificationPolicy",
    "WorkforceRegistryError",
    "advance_lifecycle",
    "alternate_agent_takeover",
    "apply_verification_decision",
    "assert_agent_selectable",
    "assert_no_automatic_cross_context",
    "assert_scopes_allow_spend",
    "assignment_authority_is_live",
    "budget_is_live",
    "budget_remaining",
    "can_safely_retry",
    "cancel_assignment",
    "classify_trust_zone",
    "create_context_package",
    "detect_need_and_create_candidate",
    "disable_workforce_agent",
    "fail_closed_on_secret_request",
    "form_pattern_team",
    "form_team",
    "get_or_create_rollup",
    "get_workforce_agent",
    "get_workforce_agent_by_key",
    "ingest_untrusted_result",
    "latest_checkpoint",
    "list_workforce_agents",
    "looks_like_prompt_injection",
    "mark_failure",
    "mark_verification",
    "minimize_for_trust_zone",
    "organization_snapshot",
    "package_context_per_member",
    "path_allowed",
    "policy_for_risk",
    "record_checkpoint",
    "record_improvement",
    "record_job_attempt",
    "record_verified_outcome",
    "refuse_role_or_tool_self_upgrade",
    "register_workforce_agent",
    "release_budget_reservation",
    "require_live_assignment_authority",
    "reserve_against_budget",
    "resolve_delegation",
    "resume_after_restart",
    "retire_workforce_agent",
    "revoke_assignment_authority",
    "run_hiring_pipeline",
    "run_low_risk_classification_slice",
    "safe_retry_same_agent",
    "score_candidates",
    "scrub_authority_mutations",
    "select_best_candidate",
    "set_cost_budget",
    "settle_budget_reservation",
    "submit_delegation_request",
    "tool_class_allowed",
    "verified_success_rate",
]
