"""MainAI V2 Autonomous Development Director (Part 1 of 2): Program, AutonomyLevel, Job/work
queue, protected artifacts, external provider leases, builder/examiner separation,
completion evidence.

Standalone, isolated, NOT imported by any production runtime path (no app.main import, no
app.guardian/app.privacy_boundary/app.sentinel/app.sovereign_identity/app.life_recovery/
app.operating_shell/app.attachment_chamber import from this package). DOES reference real
production types by name in docstrings/data (SupervisorScope, TaskScopedAuthority,
ReadinessLevel, APPROVAL_POLICIES, VerificationPolicy) without importing any of them -- this
is a new coordination tier explicitly designed to compose with real infrastructure. See
docs/mainai_v2/MAINAI_V2_AUTONOMOUS_DEVELOPMENT_DIRECTOR_RECONCILIATION.md for the design.
"""

from app.dev_director.builder_examiner import (
    new_builder_assignment,
    new_examiner_assignment,
    record_examiner_verdict,
    submit_builder_result,
)
from app.dev_director.completion_evidence import validate_completion_evidence
from app.dev_director.fix_loop import (
    MAX_FIX_ATTEMPTS,
    JobHeartbeat,
    JobLivenessAssessment,
    MaxFixAttemptsExceededError,
    assess_job_liveness,
    create_fix_job,
    handle_confirmed_abandoned_job,
    record_liveness_strike,
)
from app.dev_director.loop import (
    BLOCKED_WHILE_OFFLINE_RISK_CLASSES,
    AdapterCrashError,
    BuilderAdapter,
    ExaminerAdapter,
    TickOutcome,
    TickResult,
    is_blocked_while_offline,
    run_program_tick,
)
from app.dev_director.founder_brief import FounderBrief, generate_founder_brief
from app.dev_director.git_pr_broker import (
    GitWorktreeBrokerContract,
    PullRequestProposal,
    PullRequestProposalError,
    build_pr_proposal,
)
from app.dev_director.provider_selection import select_builder_provider
from app.dev_director.recovery import (
    ConflictingBuilderResultError,
    JobRecoveryDecision,
    RecoveryAction,
    RecoveryPlan,
    apply_pending_builder_result,
    apply_pending_examiner_verdict,
    recover_program_state,
)
from app.dev_director.job import (
    detect_job_conflicts,
    new_job,
    next_ready_job,
    recompute_program_job_index,
    transition_job,
    verify_job_event_chain_intact,
)
from app.dev_director.program import (
    new_program,
    record_budget_consumption,
    release_budget_reservation,
    reserve_from_budget,
    set_autonomy_level,
)
from app.dev_director.protected import assert_artifact_not_protected
from app.dev_director.provider_lease import (
    lease_scoped_to_original_request,
    new_external_provider_lease,
    select_failover_provider,
)
from app.dev_director.types import (
    AUTONOMY_LEVEL_APPROVAL_POLICY_KEY,
    AUTONOMY_LEVEL_REQUIRED_READINESS,
    DEFAULT_AUTONOMY_LEVEL,
    JOB_TRANSITIONS,
    LEVELS_REQUIRING_EXPLICIT_FOUNDER_AUTHORIZATION,
    PR_245_PROTECTED_ARTIFACT,
    TERMINAL_JOB_STATES,
    AutonomyLevel,
    AutonomyLevelRequiresFounderAuthorizationError,
    BudgetEnvelope,
    BudgetExceededError,
    BuilderAssignment,
    BuilderExaminerCollusionError,
    BuilderResult,
    CompletionEvidence,
    ConflictReport,
    DevDirectorError,
    ExaminerAssignment,
    ExaminerVerdict,
    ExaminerVerdictError,
    ExaminerVerdictRecord,
    ExternalProviderLease,
    Job,
    JobEvent,
    JobState,
    JobTransitionError,
    NoAvailableProvider,
    NoReadyJob,
    Program,
    ProtectedArtifact,
    ProtectedArtifactViolationError,
    ProviderCapabilityProfile,
    ProviderUsageState,
    JobTestResult,
    ValidationResult,
)

__all__ = [
    "AUTONOMY_LEVEL_APPROVAL_POLICY_KEY",
    "AUTONOMY_LEVEL_REQUIRED_READINESS",
    "BLOCKED_WHILE_OFFLINE_RISK_CLASSES",
    "DEFAULT_AUTONOMY_LEVEL",
    "MAX_FIX_ATTEMPTS",
    "JOB_TRANSITIONS",
    "LEVELS_REQUIRING_EXPLICIT_FOUNDER_AUTHORIZATION",
    "PR_245_PROTECTED_ARTIFACT",
    "TERMINAL_JOB_STATES",
    "AdapterCrashError",
    "AutonomyLevel",
    "AutonomyLevelRequiresFounderAuthorizationError",
    "BudgetEnvelope",
    "BudgetExceededError",
    "BuilderAdapter",
    "BuilderAssignment",
    "BuilderExaminerCollusionError",
    "BuilderResult",
    "CompletionEvidence",
    "ConflictingBuilderResultError",
    "ConflictReport",
    "DevDirectorError",
    "ExaminerAdapter",
    "ExaminerAssignment",
    "ExaminerVerdict",
    "ExaminerVerdictError",
    "ExaminerVerdictRecord",
    "ExternalProviderLease",
    "FounderBrief",
    "GitWorktreeBrokerContract",
    "Job",
    "JobEvent",
    "JobHeartbeat",
    "JobLivenessAssessment",
    "JobRecoveryDecision",
    "JobState",
    "JobTransitionError",
    "MaxFixAttemptsExceededError",
    "NoAvailableProvider",
    "NoReadyJob",
    "Program",
    "PullRequestProposal",
    "PullRequestProposalError",
    "RecoveryAction",
    "RecoveryPlan",
    "ProtectedArtifact",
    "ProtectedArtifactViolationError",
    "ProviderCapabilityProfile",
    "ProviderUsageState",
    "JobTestResult",
    "ValidationResult",
    "apply_pending_builder_result",
    "apply_pending_examiner_verdict",
    "assert_artifact_not_protected",
    "assess_job_liveness",
    "build_pr_proposal",
    "create_fix_job",
    "generate_founder_brief",
    "recover_program_state",
    "detect_job_conflicts",
    "handle_confirmed_abandoned_job",
    "is_blocked_while_offline",
    "lease_scoped_to_original_request",
    "new_builder_assignment",
    "new_examiner_assignment",
    "new_external_provider_lease",
    "new_job",
    "new_program",
    "next_ready_job",
    "recompute_program_job_index",
    "record_budget_consumption",
    "record_examiner_verdict",
    "record_liveness_strike",
    "release_budget_reservation",
    "reserve_from_budget",
    "run_program_tick",
    "select_builder_provider",
    "select_failover_provider",
    "set_autonomy_level",
    "submit_builder_result",
    "TickOutcome",
    "TickResult",
    "transition_job",
    "validate_completion_evidence",
    "verify_job_event_chain_intact",
]
