"""MainAI Operating Shell (MainAI V2, Stages V2-I1..I7): declarative workspace commands,
control arbitration, action risk/preview, workspace state/memory, Intent Objects, context
resolution, show-don't-tell evidence surfaces, internal agent delegation boundary, and
workspace restore planning.

Standalone, isolated, NOT imported by any production runtime path (no app.main import, no
app.guardian/app.privacy_boundary/app.sentinel/app.sovereign_identity/app.life_recovery
import from this package). See docs/mainai_v2/MAINAI_V2_ORB_OPERATING_SHELL.md for the
design.
"""

from app.operating_shell.context import resolve_reference
from app.operating_shell.control import (
    ControlArbitrationState,
    ResumeDecision,
    end_takeover,
    new_control_state,
    on_user_input,
    resume_from_current_state,
)
from app.operating_shell.delegation import aggregate_for_user, record_delegation_result
from app.operating_shell.evidence import (
    build_evidence_surface,
    request_diff_view,
    request_incident_evidence,
    request_memory_evidence,
)
from app.operating_shell.intent import (
    IntentTransitionError,
    abandon,
    active_intents_for_owner,
    advance_to_active,
    advance_to_planned,
    complete,
    create_intent_from_expression,
    detect_dependency_cycle,
    find_missing_dependencies,
    has_authority_from_next_action,
    mark_blocked,
    record_understanding,
    resolve_intent_by_title_fragment,
    supersede_intent,
    unblock,
)
from app.operating_shell.intent import from_snapshot as intent_from_snapshot
from app.operating_shell.intent import to_snapshot as intent_to_snapshot
from app.operating_shell.restore import plan_workspace_restore, resource_status
from app.operating_shell.risk import (
    ALLOWED,
    DENIED,
    ActionAuthorityPolicy,
    build_action_preview,
    build_action_result,
    classify_action_risk,
    evaluate_action_authority,
    record_action_receipt,
    require_preview_for_consequential_action,
    require_root_sensitive_policy,
    verify_receipt_chain_intact,
)
from app.operating_shell.types import (
    ACTION_RISK_ORDER,
    CONSEQUENTIAL_AND_ABOVE,
    DEFAULT_ACTION_RISK,
    NON_TERMINAL_INTENT_STATES,
    TERMINAL_INTENT_STATES,
    ActionPreview,
    ActionReceipt,
    ActionRiskLevel,
    AmbiguousResolution,
    ConsequentialActionRequiresPreviewError,
    ControlState,
    EvidenceSurfaceKind,
    EvidenceSurfaceRequest,
    EvidenceSurfaceResult,
    IntentBlocker,
    IntentGraphError,
    IntentHistoryEntry,
    IntentObject,
    IntentState,
    InternalDelegationResult,
    MalformedIntentSnapshotError,
    MalformedWorkspaceSnapshotError,
    OperatingShellError,
    PausedAction,
    PolicyNotWiredError,
    ReferenceKind,
    ResolvedReference,
    ResourceAvailability,
    RestoreResourceStatus,
    RestoreResult,
    UserFacingAnswer,
    UserInputSignal,
    WorkspaceAction,
    WorkspaceActionResult,
    WorkspaceActionType,
    WorkspaceCommand,
    WorkspaceContext,
    WorkspaceDocument,
    WorkspaceFocus,
    WorkspaceRestorePlan,
    WorkspaceSecretShapedContentError,
    WorkspaceSelection,
    WorkspaceTarget,
    WorkspaceWindow,
)
from app.operating_shell.workspace import (
    WorkspaceMemorySummary,
    WorkspaceState,
    new_workspace_state,
    record_recent_command,
    reject_secret_shaped_content,
    restore_workspace_state_does_not_reauthorize,
    set_current_task,
    summarize_workspace_memory,
)
from app.operating_shell.workspace import from_snapshot as workspace_from_snapshot
from app.operating_shell.workspace import to_snapshot as workspace_to_snapshot

__all__ = [
    "ACTION_RISK_ORDER",
    "ALLOWED",
    "CONSEQUENTIAL_AND_ABOVE",
    "DEFAULT_ACTION_RISK",
    "DENIED",
    "NON_TERMINAL_INTENT_STATES",
    "TERMINAL_INTENT_STATES",
    "ActionAuthorityPolicy",
    "ActionPreview",
    "ActionReceipt",
    "ActionRiskLevel",
    "AmbiguousResolution",
    "ConsequentialActionRequiresPreviewError",
    "ControlArbitrationState",
    "ControlState",
    "EvidenceSurfaceKind",
    "EvidenceSurfaceRequest",
    "EvidenceSurfaceResult",
    "IntentBlocker",
    "IntentGraphError",
    "IntentHistoryEntry",
    "IntentObject",
    "IntentState",
    "IntentTransitionError",
    "InternalDelegationResult",
    "MalformedIntentSnapshotError",
    "MalformedWorkspaceSnapshotError",
    "OperatingShellError",
    "PausedAction",
    "PolicyNotWiredError",
    "ReferenceKind",
    "ResolvedReference",
    "ResourceAvailability",
    "RestoreResourceStatus",
    "RestoreResult",
    "ResumeDecision",
    "UserFacingAnswer",
    "UserInputSignal",
    "WorkspaceAction",
    "WorkspaceActionResult",
    "WorkspaceActionType",
    "WorkspaceCommand",
    "WorkspaceContext",
    "WorkspaceDocument",
    "WorkspaceFocus",
    "WorkspaceMemorySummary",
    "WorkspaceRestorePlan",
    "WorkspaceSecretShapedContentError",
    "WorkspaceSelection",
    "WorkspaceState",
    "WorkspaceTarget",
    "WorkspaceWindow",
    "abandon",
    "active_intents_for_owner",
    "advance_to_active",
    "advance_to_planned",
    "aggregate_for_user",
    "build_action_preview",
    "build_action_result",
    "build_evidence_surface",
    "classify_action_risk",
    "complete",
    "create_intent_from_expression",
    "detect_dependency_cycle",
    "end_takeover",
    "evaluate_action_authority",
    "find_missing_dependencies",
    "has_authority_from_next_action",
    "intent_from_snapshot",
    "intent_to_snapshot",
    "mark_blocked",
    "new_control_state",
    "new_workspace_state",
    "on_user_input",
    "plan_workspace_restore",
    "record_action_receipt",
    "record_delegation_result",
    "record_recent_command",
    "record_understanding",
    "reject_secret_shaped_content",
    "request_diff_view",
    "request_incident_evidence",
    "request_memory_evidence",
    "resolve_intent_by_title_fragment",
    "resolve_reference",
    "resource_status",
    "restore_workspace_state_does_not_reauthorize",
    "resume_from_current_state",
    "require_preview_for_consequential_action",
    "require_root_sensitive_policy",
    "set_current_task",
    "summarize_workspace_memory",
    "supersede_intent",
    "unblock",
    "verify_receipt_chain_intact",
    "workspace_from_snapshot",
    "workspace_to_snapshot",
]
